export const characteristics = [
  'Fumante',
  'Bebe',
  'Tem animais',
  'Tem filhos',
  'Gamer',
  'Estuda',
  'Trabalha',
  'HomeOffice',
  'Visitas frequentes',
  'Festeira',
  'Barulhenta',
  'Bagunçada',
  'Organizada',
  'Deficiente',
];
